### ISSUE TITLE
Some field references aren't remapped to official mappings

### ISSUE THREAD

**Issue by coehlrich** [marchermans/JarAwareMapping#7]
When updating from 23w14a to 23w16a the `RealmsMainScreen.lambda$addMiddleButtons$4` lambda got a different parameter name even after remapping to official mappings though none of the contents (or the name) changed. This seems to be due to the lambda refrencing the `Screen.minecraft` field which compiled to having the owner set to `RealmsMainScreen` so asm passes that as the owner and both https://github.com/marchermans/JarAwareMapping/blob/master/jam/src/main/java/com/ldtteam/jam/rename/EnhancedClassRemapper.java and https://github.com/marchermans/JarAwareMapping/blob/master/mcpconfig/src/main/java/com/ldtteam/jam/mcpconfig/TSRGRemapper.java don't check any super classes for if they contain the referenced field instead.

MCPConfig update run: https://github.com/coehlrich/MCPConfig/actions/runs/4754935472
MappingToy metadata is the `mapping-metadata` artifact.

**Comment by marchermans** [comment]
@coehlrich Any example of how this is done right then?

**Comment by coehlrich** [comment]
ForgeAutoRenamingTool adds all fields from super classes and interfaces into sub classes
https://github.com/MinecraftForge/ForgeAutoRenamingTool/blob/master/src/main/java/net/minecraftforge/fart/internal/EnhancedRemapper.java#L187-L211
